### ISSUE TITLE
Problem with right side of the room

### ISSUE THREAD

**Issue by WhoAmI125** [WhoAmI125/RoomEscape#14]
For each room#.html, the right side seems to crash when it done by "px" depending on the computer because the style.css is "left: #px"

If the object is placed on the right side, use "right: #px" to avoid the crash

**Look at the clock**

done in left:px

![image](https://user-images.githubusercontent.com/87934953/169101486-a0b9e5fa-8482-4a11-bad0-8157a0074146.png)

done in right:px

![image](https://user-images.githubusercontent.com/87934953/169101673-fa2627e4-33b5-4044-86a1-d14a22c48aef.png)

link to bug: 
- 5f64a6536533d0fd3cf9c71bc1d34d787a0e627a
- 026fc48e2636fbfe9d2bd13d5fa8b377aee8f71a

**Comment by user13571** [comment]
I think this is happening because of the difference between computer environment.
I fixed my error temporary using % setting.

**Comment by user13571** [comment]
![image](https://user-images.githubusercontent.com/100356286/169179324-7b828c6f-dacb-429f-b0b1-0f5e422fdff8.png)
Modified one looks like this in my computer.

**Comment by WhoAmI125** [comment]
@user13571 also right: px; works, by this I think it does not crash even if we change the window size
